### ISSUE TITLE
Standardize collection APIs

### ISSUE THREAD

**Issue by gmelodie** [application-research/estuary#173]
Collections APIs use two main arguments: 
- `collection` or `col` to refer to the collection's UUID
- `collectionPath` or `dir` to refer to the path of a certain content inside a collection

We should name those things consistently, not have two names for the same thing.

**Comment by aeryz** [comment]
- I think for collection UUID, `collection` should be used. For example I was playing around with estuary for the first time and thought for a second that `col` means `column`. `collection` is definitely more clear.
- Also `dir` is short version of `directory` which is confusing because absolute path to files also work. (see: `/collections/fs/list`) so I think instead of `dir`, `path` should be used (taking [this issue](https://github.com/application-research/estuary/issues/186) into account).

I can create a PR for both issues if there are no other ideas about naming.
